stages:
  - build
  - test

build:
  image: python:2
  stage: build
  script:
    - apt-get update
    - apt-get -y install python-pip
    - apt-get -y install python-tk
    - ./install.sh
  cache:
    paths:
      - .local
      -  /usr/lib/python2.7

test:
  stage: test
  dependencies:
    - build
  script:
    - apt-get update
    - apt-get -y install openjdk-8-jre
    - apt-get -y install python-pytest
    - cd Tests
    - pytest --ignore=Tests/test_Search.py
    - pytest Tests/test_Search.py::SearchOracleFunctionTestCase