stages:
  - build
  - test

build:
  image: python:2
  stage: build
  script:
    - apt-get update
    - apt-get -y install openjdk-8-jre
    - apt-get -y install python-pip
    - apt-get -y install python-tk
    - apt-get -y install python-pytest
    - ./install.sh

test:
  stage: test
  dependencies:
    - build
  script:
    - cd Tests
    - pytest --ignore=Tests/test_Search.py
    - pytes Tests/test_Search.py::SearchOracleFunctionTestCase