image: python:2

stages:
  - build_test

build_test:
  stage: build_test
  script:
    - apt-get update
    - apt-get -y install openjdk-8-jre
    - apt-get -y install python-pip
    - apt-get -y install python-tk
    - apt-get -y install python-pytest
    - ./install.sh
    - pytest --ignore=Tests/test_Search_ResultSet.py::test_plot_2D --ignore=Tests/test_Search_ResultSet.py::test_plot_3D --ignore=Tests/test_Search.py
    - pytest Tests/test_Search.py::SearchOracleFunctionTestCase